// The committed diagram asset (viz/public/diagram.json), generated by
// scripts/gen_diagram.py from the static GTFS feed. Keep these types in
// lockstep with training/diagram.py:to_json — that function is the producer.
//
// The asset is geometry only: no status, no timestamp. It changes when the MTA
// timetable changes, so it's fetched once per page load and never polled.

export interface DiagramStation {
  name: string;
  x: number;
  y: number;
  routes: string[];
}

export interface DiagramRoute {
  name: string;
  color: string;
}

// One route's drawable run between two adjacent stations. `keys` maps a
// direction to the `segment_flow.segments` key that measures this pair in that
// direction — absent for a direction the timetable doesn't schedule here.
export interface DiagramEdge {
  route: string;
  a: string;
  b: string;
  path: Array<[number, number]>;
  keys: Partial<Record<Direction, string>>;
  // Scheduled run time for this hop from the static timetable, in whole
  // seconds, nested by NYCT service class and then by direction. Any level can
  // be absent — a class the route doesn't run, a direction the timetable
  // doesn't time, or (on an asset generated before timings shipped) the whole
  // field. Every absence means "no timing", never zero.
  seconds?: Partial<Record<ServiceClass, Partial<Record<Direction, number>>>>;
}

// A component drawn away from its true position. The renderer must outline and
// label it: an inset that isn't marked as one is a map that lies about where
// Staten Island is.
export interface DiagramInset {
  routes: string[];
  box: [number, number, number, number];
  scale: number;
}

export interface Diagram {
  feed_version: { version: string; start: string | null; end: string | null };
  view_box: [number, number, number, number];
  routes: Record<string, DiagramRoute>;
  stations: Record<string, DiagramStation>;
  edges: DiagramEdge[];
  insets: DiagramInset[];
}

// The two directions a segment cell can be keyed on. The runtime tuple lives
// in ./segments with the rest of the status vocabulary, so this module stays
// type-only for consumers that don't fetch.
export type Direction = "north" | "south";

// The service classes NYCT writes separate timetables for. Saturday and Sunday
// are distinct schedules, not one "weekend" schedule. Note that some holidays
// run a weekend timetable on a calendar weekday, which the asset can't say and
// no consumer should pretend to know.
export type ServiceClass = "weekday" | "saturday" | "sunday";

export async function fetchDiagram(): Promise<Diagram> {
  const res = await fetch("/diagram.json", { cache: "force-cache" });
  if (!res.ok) throw new Error(`diagram fetch failed: ${res.status}`);
  return res.json();
}

// SVG `d` for an edge. A path, not a line, because the geometry contract allows
// more than two points: swapping the layout for an octilinear one is a change
// to training/diagram.py alone, and this keeps drawing it.
export function edgePath(edge: DiagramEdge): string {
  return edge.path.map(([x, y], i) => `${i === 0 ? "M" : "L"}${x} ${y}`).join(" ");
}
