// The committed station-maintenance sidecar (viz/public/station_maintenance.json),
// generated by training/station_maintenance.py from our own R2 archives. Keep
// these types in lockstep with that script's build_doc step — it is the producer.
//
// Derived maintenance history for a stop: elevator/escalator outages active this
// month with the median time-to-repair, and planned-work closures this year.
// Reduced from the hourly E&E archive and the parsed planned-work answer key,
// then committed as a static asset — the same contract as station_facts.json:
// fetched once per page load, cached, and never polled. Keyed by GTFS parent
// stop id, so the Station page reads it with the same id as its other data.

/** One stop's maintenance tally. `median_repair_hours` and `resolved_outages`
 * describe the outages that both broke and cleared inside the month window; a
 * still-open outage counts toward the outage totals but carries no repair time,
 * so `median_repair_hours` is null when nothing resolved. */
export interface StationMaintenanceEntry {
  elevator_outages: number;
  escalator_outages: number;
  resolved_outages: number;
  median_repair_hours: number | null;
  planned_closures: number;
}

/** The window an ISO-bounded metric describes. */
export interface MaintenanceWindow {
  start: string;
  end: string;
}

export interface StationMaintenance {
  schema_version: string;
  generated_at: number;
  source: { ene: string; windows: string };
  // The month the outage counts cover and the year the closures cover, both in
  // ET wall time. `coverage` is what the archive actually holds — collection
  // began in May 2026 — so a short archive is visible as such rather than read
  // as a quiet station.
  outage_window: MaintenanceWindow;
  closure_window: MaintenanceWindow;
  coverage: { ene: MaintenanceWindow | null; windows: MaintenanceWindow | null };
  stations: Record<string, StationMaintenanceEntry>;
  n_stations: number;
}

// Module-scoped singleton: the asset is fetched and parsed exactly once per load
// and shared. Failures are not cached, so a transient error doesn't wedge the
// hook for the rest of the session. Mirrors fetchStationFacts.
let maintenancePromise: Promise<StationMaintenance> | null = null;

export function fetchStationMaintenance(): Promise<StationMaintenance> {
  if (!maintenancePromise) {
    // Default cache semantics (not force-cache): a browser holding an older copy
    // must be able to revalidate against a regenerated asset. The module-scoped
    // promise is what keeps it to one fetch per load.
    maintenancePromise = fetch("/station_maintenance.json")
      .then((res) => {
        if (!res.ok) throw new Error(`station maintenance fetch failed: ${res.status}`);
        return res.json() as Promise<StationMaintenance>;
      })
      .then((doc) => {
        if (doc.stations === undefined) {
          throw new Error(
            "station_maintenance.json is missing `stations` — the cached copy " +
              "predates the current shape. Hard-reload to pick up the new one.",
          );
        }
        return doc;
      })
      .catch((e: unknown) => {
        maintenancePromise = null;
        throw e;
      });
  }
  return maintenancePromise;
}
