// Cross-language parity: the viz dwell-mixture math must reproduce, case for
// case, the outputs Python recorded in tests/fixtures/parity_dwell.json.
//
// The fixture pins the atom + left-truncated log-logistic mixture (point mass
// at one publisher tick, mixed with a log-logistic tail refit conditional on
// T > 1 tick) and the dwell_cdf lower-boundary fix that goes with it. It is
// generated by scripts/gen_dwell_parity_fixture.py and verified on the Python
// side by tests/test_dwell_parity.py, and on the Worker side by
// worker/test/dwell_parity.test.ts. This is the viz half of the pin — if
// viz/lib/dwell.ts drifts from training/dwell.py, it fails here.
//
// viz/lib/dwell.ts has no standalone conditional-remaining-quantile export
// (nothing in the dashboard needs it yet, unlike worker/src/dwell.ts's
// conditionalRecovery), so this test replays every case EXCEPT the
// conditional_remaining_quantile ones.
//
// Regenerate the fixture with: uv run python -m scripts.gen_dwell_parity_fixture

import { test } from "node:test";
import assert from "node:assert/strict";
import fixture from "../../tests/fixtures/parity_dwell.json" with { type: "json" };
import { dwellCdf, mixtureQuantile, mixtureSurvival, pLeaveBy } from "../lib/dwell.ts";

type Atom = { p: number; sec: number };

// The fixture is a flat list of labelled cases; `inputs` varies per `fn`, so
// every field is optional here and each branch below reads only the ones the
// function it dispatches to actually needs.
interface DwellCase {
  label: string;
  fn: string;
  inputs: {
    curve_sec?: number[];
    x?: number;
    t?: number;
    shape?: number;
    scale?: number;
    atom_p?: number;
    atom_sec?: number;
    u?: number;
    elapsed_sec?: number;
    horizon_sec?: number;
    q?: number;
    tail_ll?: number[] | null;
    atom?: Atom | null;
  };
  expected: number | null;
}

const rawCases = fixture.cases;
const cases = rawCases as unknown as DwellCase[];

function evaluate(c: DwellCase): number {
  const { inputs } = c;
  switch (c.fn) {
    case "dwell_cdf":
      return dwellCdf(inputs.curve_sec!, inputs.x!);
    case "mixture_survival":
      return mixtureSurvival(
        inputs.t!,
        inputs.shape!,
        inputs.scale!,
        inputs.atom_p!,
        inputs.atom_sec!,
      );
    case "mixture_quantile":
      return mixtureQuantile(
        inputs.u!,
        inputs.shape!,
        inputs.scale!,
        inputs.atom_p!,
        inputs.atom_sec!,
      );
    case "p_leave_by":
      return pLeaveBy(
        inputs.curve_sec!,
        inputs.elapsed_sec!,
        inputs.horizon_sec!,
        inputs.tail_ll ?? undefined,
        inputs.atom ?? undefined,
      );
    default:
      throw new Error(`unsupported fixture fn in viz: ${c.fn}`);
  }
}

const REPLAYABLE_FNS: Record<string, true> = {
  dwell_cdf: true,
  mixture_survival: true,
  mixture_quantile: true,
  p_leave_by: true,
};

test("dwell mixture parity with training/dwell.py", () => {
  const replayable = cases.filter((c) => REPLAYABLE_FNS[c.fn]);
  assert.ok(replayable.length > 0, "fixture produced no cases viz/lib/dwell.ts can replay");
  for (const c of replayable) {
    const actual = evaluate(c);
    assert.ok(
      Math.abs(actual - (c.expected as number)) <= 1e-9,
      `${c.label}: got ${actual}, want ${c.expected}`,
    );
  }
});

test("F(atom_sec) == atom_p exactly at the boundary case", () => {
  const boundary = cases.find((c) => c.label === "atom_boundary_survival_at_atom_sec")!;
  const survivalAtAtomSec = boundary.expected as number;
  const atomP = boundary.inputs.atom_p as number;
  assert.ok(Math.abs(1 - survivalAtAtomSec - atomP) <= 1e-9);
});
