// Cross-language parity: the viz movement classifier must reproduce, case for
// case, the labels Python recorded in tests/fixtures/parity_movement.json.
//
// The fixture pins the per-(route, direction) Beta-Binomial call — a single
// tick's advance count regularized toward the cell baseline p0, called
// disrupted only when the posterior sits at/under DISRUPTED_RATIO * p0 AND the
// low count is significant (binomial lower tail <= CLASSIFY_ALPHA), abstaining
// below MIN_MATCHED_TRIPS. It is generated by
// scripts/gen_movement_parity_fixture.py from training/load_r2.py's
// classify_direction, verified on the Python side by
// tests/test_movement_parity.py and on the Worker side by
// worker/test/movement_parity.test.ts. This is the viz half of the pin — if
// viz/lib/movement.ts drifts from load_r2.py, it fails here.
//
// A case carries a bare p0; classifyDirection reads only p0 off a cell, so each
// case rebuilds the trainer's cell shape (alpha/beta/n for the type). p0 null
// means "no baseline cell" -> undefined.
//
// Regenerate the fixture with: uv run python -m scripts.gen_movement_parity_fixture

import { test } from "node:test";
import assert from "node:assert/strict";
import fixture from "../../tests/fixtures/parity_movement.json" with { type: "json" };
import { classifyDirection, type AdvanceBaselineCell } from "../lib/movement.ts";

interface MovementCase {
  label: string;
  fn: string;
  inputs: { advanced: number; stalled: number; p0: number | null };
  expected: "normal" | "disrupted" | null;
}

const cases = fixture.cases as unknown as MovementCase[];

function cell(p0: number | null): AdvanceBaselineCell | undefined {
  // Only p0 drives classifyDirection; alpha/beta/n are for type completeness.
  return p0 === null ? undefined : { p0, alpha: 50 * p0, beta: 50 * (1 - p0), n: 50 };
}

test("movement classifier parity with training/load_r2.py classify_direction", () => {
  for (const c of cases) {
    const actual = classifyDirection(c.inputs.advanced, c.inputs.stalled, cell(c.inputs.p0));
    assert.equal(actual, c.expected, `${c.label} drifted`);
  }
});
