/**
 * Cross-language parity: the Worker arrivals derivation must reproduce, stop
 * for stop, the surface Python recorded in tests/fixtures/parity_arrivals.json.
 *
 * The fixture pins the shared rule set — express fold, stop-id keying incl. the
 * direction suffix, the SKIPPED / timeless / past / beyond-horizon drops,
 * per-trip dedupe, soonest-first ordering, the N cap. It is
 * generated by scripts/gen_arrivals_parity_fixture.py from
 * src/momentarily/arrivals.py and verified on the Python side by
 * tests/test_arrivals_parity.py. If worker/src/arrivals.ts drifts from that
 * mirror, it fails here.
 *
 * Regenerate with: uv run python -m scripts.gen_arrivals_parity_fixture
 */

import { describe, expect, test } from 'vitest';

import fixture from '../../tests/fixtures/parity_arrivals.json';
import { type Arrivals, deriveArrivals } from '../src/arrivals';
import type { TripLite } from '../src/gtfsrt';

interface TripJson {
  route_id: string;
  trip_id: string;
  direction: number | null;
  stop_times: {
    stop_id: string;
    arrival: number | null;
    departure: number | null;
    schedule_relationship: number;
  }[];
}

function toTrip(raw: TripJson): TripLite {
  return {
    routeId: raw.route_id,
    tripId: raw.trip_id,
    isAssigned: false, // unused by deriveArrivals; the type requires it
    direction: raw.direction,
    stopCount: raw.stop_times.length,
    stopTimes: raw.stop_times.map((st) => ({
      stopId: st.stop_id,
      arrival: st.arrival,
      departure: st.departure,
      scheduleRelationship: st.schedule_relationship,
    })),
  };
}

describe('arrivals derivation parity with src/momentarily/arrivals.py', () => {
  test('reproduces the fixture arrivals surface', () => {
    const trips = (fixture.trips as TripJson[]).map(toTrip);
    const actual = deriveArrivals(trips, fixture.now);
    expect(actual).toEqual(fixture.expected as unknown as Arrivals);
  });
});
