/**
 * Cross-language parity: the TS dwell-mixture math must reproduce, case for
 * case, the outputs Python recorded in tests/fixtures/parity_dwell.json.
 *
 * The fixture pins the atom + left-truncated log-logistic mixture (point mass
 * at one publisher tick, mixed with a log-logistic tail refit conditional on
 * T > 1 tick) and the dwell_cdf lower-boundary fix that goes with it. It is
 * generated by scripts/gen_dwell_parity_fixture.py and verified on the Python
 * side by tests/test_dwell_parity.py. This test is the Worker half of the
 * pin — if worker/src/dwell.ts drifts from training/dwell.py, it fails here.
 *
 * Regenerate the fixture with: uv run python -m scripts.gen_dwell_parity_fixture
 */

import { describe, expect, test } from 'vitest';

import fixture from '../../tests/fixtures/parity_dwell.json';
import type { ConditionalRecovery } from '../src/dwell';
import {
  conditionalRecovery,
  dwellCdf,
  mixtureQuantile,
  mixtureSurvival,
  pLeaveBy,
} from '../src/dwell';

type Atom = { p: number; sec: number };

// The fixture is a flat list of labelled cases; `inputs` varies per `fn`, so
// every field is optional here and each branch below reads only the ones the
// function it dispatches to actually needs.
interface DwellCase {
  label: string;
  fn: string;
  inputs: {
    curve_sec?: number[];
    x?: number;
    t?: number;
    shape?: number;
    scale?: number;
    atom_p?: number;
    atom_sec?: number;
    u?: number;
    elapsed_sec?: number;
    horizon_sec?: number;
    q?: number;
    tail_ll?: number[] | null;
    atom?: Atom | null;
  };
  expected: number | null;
}

const rawCases = fixture.cases;
const cases = rawCases as unknown as DwellCase[];

// conditional_remaining_quantile has no standalone TS export — it's the same
// math conditionalRecovery already computes per fixed quantile. The fixture
// only ever asks for q in {0.25, 0.5, 0.75}, which are exactly the three
// fields ConditionalRecovery publishes.
function conditionalRecoveryField(q: number): keyof ConditionalRecovery {
  if (q === 0.25) return 'q25_sec';
  if (q === 0.5) return 'median_sec';
  if (q === 0.75) return 'q75_sec';
  throw new Error(`no ConditionalRecovery field for q=${q}`);
}

function evaluate(c: DwellCase): number | null {
  const { inputs } = c;
  switch (c.fn) {
    case 'dwell_cdf':
      return dwellCdf(inputs.curve_sec!, inputs.x!);
    case 'mixture_survival':
      return mixtureSurvival(
        inputs.t!,
        inputs.shape!,
        inputs.scale!,
        inputs.atom_p!,
        inputs.atom_sec!,
      );
    case 'mixture_quantile':
      return mixtureQuantile(
        inputs.u!,
        inputs.shape!,
        inputs.scale!,
        inputs.atom_p!,
        inputs.atom_sec!,
      );
    case 'p_leave_by':
      return pLeaveBy(
        inputs.curve_sec!,
        inputs.elapsed_sec!,
        inputs.horizon_sec!,
        inputs.tail_ll ?? undefined,
        inputs.atom ?? undefined,
      );
    case 'conditional_remaining_quantile': {
      const recovery = conditionalRecovery(
        inputs.curve_sec!,
        inputs.elapsed_sec!,
        inputs.tail_ll ?? undefined,
        inputs.atom ?? undefined,
      );
      return recovery === null ? null : recovery[conditionalRecoveryField(inputs.q!)];
    }
    default:
      throw new Error(`unknown fixture fn: ${c.fn}`);
  }
}

function expectWithinAbsTol(actual: number, expected: number, label: string): void {
  expect(Math.abs(actual - expected), label).toBeLessThanOrEqual(1e-9);
}

describe('dwell mixture parity with training/dwell.py', () => {
  test('reproduces every recorded case to absolute tolerance 1e-9', () => {
    for (const c of cases) {
      const actual = evaluate(c);
      if (c.expected === null) {
        expect(actual, c.label).toBeNull();
      } else {
        expect(actual, c.label).not.toBeNull();
        expectWithinAbsTol(actual as number, c.expected, c.label);
      }
    }
  });

  test('F(atom_sec) == atom_p exactly at the boundary case', () => {
    const boundary = cases.find((c) => c.label === 'atom_boundary_survival_at_atom_sec')!;
    const survivalAtAtomSec = boundary.expected as number;
    const atomP = boundary.inputs.atom_p as number;
    expectWithinAbsTol(1 - survivalAtAtomSec, atomP, boundary.label);
  });
});
