/**
 * Cross-language parity: the Worker movement classifier must reproduce, case
 * for case, the labels Python recorded in tests/fixtures/parity_movement.json.
 *
 * The fixture pins the per-(route, direction) Beta-Binomial call — a single
 * tick's advance count regularized toward the cell baseline p0, called
 * disrupted only when the posterior sits at/under DISRUPTED_RATIO * p0 AND the
 * low count is significant (binomial lower tail <= CLASSIFY_ALPHA), abstaining
 * below MIN_MATCHED_TRIPS. It is generated by
 * scripts/gen_movement_parity_fixture.py from training/load_r2.py's
 * classify_direction and verified on the Python side by
 * tests/test_movement_parity.py. This is the Worker half of the pin — if
 * worker/src/movement_state.ts drifts from load_r2.py, it fails here.
 *
 * classifyAdvance takes p0 directly and has no no-baseline path (that guard
 * lives in the unexported classifyDirection), so the null-p0 case is skipped.
 *
 * Regenerate the fixture with: uv run python -m scripts.gen_movement_parity_fixture
 */

import { describe, expect, test } from 'vitest';

import fixture from '../../tests/fixtures/parity_movement.json';
import { classifyAdvance } from '../src/movement_state';

interface MovementCase {
  label: string;
  fn: string;
  inputs: { advanced: number; stalled: number; p0: number | null };
  expected: 'normal' | 'disrupted' | null;
}

const cases = fixture.cases as unknown as MovementCase[];

describe('movement classifier parity with training/load_r2.py classify_direction', () => {
  for (const c of cases) {
    // classifyAdvance has no no-baseline path; Python/viz cover the null cell.
    if (c.inputs.p0 === null) continue;
    test(c.label, () => {
      const actual = classifyAdvance(c.inputs.advanced, c.inputs.stalled, c.inputs.p0 as number);
      expect(actual, c.label).toBe(c.expected);
    });
  }
});
