/**
 * Cross-language parity: the TS forward filter must reproduce the outputs
 * Python recorded in tests/fixtures/parity_forward.json.
 *
 * The fixture is generated by scripts/gen_parity_fixture.py and verified on the
 * Python side by tests/test_parity.py. This test is the TS half of the pin —
 * if worker/src/hmm.ts drifts from src/momentarily/hmm.py, it fails here.
 *
 * Regenerate the fixture with: uv run python -m scripts.gen_parity_fixture
 */

import { describe, expect, test } from 'vitest';

import fixture from '../../tests/fixtures/parity_forward.json';
import type {
  EmissionParams,
  FilterState,
  HMMParams,
  Observation,
  PublishedState,
} from '../src/hmm';
import {
  expectedDwellTicks,
  forwardStep,
  initialPublishedState,
  projectForward,
} from '../src/hmm';

type Vec3 = [number, number, number];

function vec3(a: number[]): Vec3 {
  return [a[0]!, a[1]!, a[2]!];
}

function toParams(p: (typeof fixture)['params']): HMMParams {
  const e = p.emissions;
  const emissions: EmissionParams = {
    poisson_lambda: vec3(e.poisson_lambda),
    gamma_alpha: vec3(e.gamma_alpha),
    gamma_beta: vec3(e.gamma_beta),
    bernoulli_p: vec3(e.bernoulli_p),
    bernoulli_p_delays: vec3(e.bernoulli_p_delays),
    bernoulli_p_service_change: vec3(e.bernoulli_p_service_change),
    bernoulli_p_planned: vec3(e.bernoulli_p_planned),
  };
  return {
    transition: [vec3(p.transition[0]!), vec3(p.transition[1]!), vec3(p.transition[2]!)],
    initial: vec3(p.initial),
    emissions,
  };
}

type RawObs = {
  alert_count: number;
  severity_sum: number;
  has_suspended_alert: boolean;
  has_delays: boolean;
  has_service_change: boolean;
  has_planned: boolean;
  tod_bin: number;
};

function toObs(o: RawObs | null): Observation | null {
  return o === null ? null : { ...o };
}

// Combined absolute + relative tolerance: probabilities span O(1) down to
// ~1e-83, so a pure absolute check is meaningless for the large values and a
// pure relative check is noise for the vanishingly small ones.
function expectClose(actual: number, expected: number): void {
  const tol = 1e-9 + 1e-9 * Math.abs(expected);
  expect(Math.abs(actual - expected)).toBeLessThan(tol);
}

describe('Python <-> TS forward-filter parity', () => {
  const params = toParams(fixture.params);
  const observations = fixture.observations.map((o) => toObs(o as RawObs | null));

  test('forwardStep reproduces every recorded step', () => {
    let state: FilterState = {
      probabilities: vec3(fixture.initial_filter.probabilities),
      regime_entered_at: fixture.initial_filter.regime_entered_at,
      last_updated_at: fixture.initial_filter.last_updated_at,
    };
    let published: PublishedState = initialPublishedState(state);

    observations.forEach((obs, i) => {
      const now = fixture.start_now + (i + 1) * fixture.tick_seconds;
      const result = forwardStep(state, published, obs, params, now);
      state = result.state;
      published = result.published;

      const expected = fixture.expected_steps[i]!;
      expectClose(state.probabilities[0], expected.filter.probabilities[0]!);
      expectClose(state.probabilities[1], expected.filter.probabilities[1]!);
      expectClose(state.probabilities[2], expected.filter.probabilities[2]!);
      expect(state.regime_entered_at).toBe(expected.filter.regime_entered_at);
      expect(state.last_updated_at).toBe(expected.filter.last_updated_at);
      expect(published.label).toBe(expected.published.label);
      expect(published.pending_state).toBe(expected.published.pending_state);
      expect(published.pending_streak).toBe(expected.published.pending_streak);
      expect(published.last_updated_at).toBe(expected.published.last_updated_at);
    });
  });

  test('projectForward and expectedDwellTicks match from the final state', () => {
    // Replay to the final state.
    let state: FilterState = {
      probabilities: vec3(fixture.initial_filter.probabilities),
      regime_entered_at: fixture.initial_filter.regime_entered_at,
      last_updated_at: fixture.initial_filter.last_updated_at,
    };
    let published: PublishedState = initialPublishedState(state);
    observations.forEach((obs, i) => {
      const now = fixture.start_now + (i + 1) * fixture.tick_seconds;
      const result = forwardStep(state, published, obs, params, now);
      state = result.state;
      published = result.published;
    });

    for (const [ticks, expectedProbs] of Object.entries(fixture.expected_projections)) {
      const projected = projectForward(state, params, Number(ticks));
      expectClose(projected[0], expectedProbs[0]!);
      expectClose(projected[1], expectedProbs[1]!);
      expectClose(projected[2], expectedProbs[2]!);
    }

    const dwell = expectedDwellTicks(state, params);
    expect(dwell.median).toBe(fixture.expected_dwell.median);
    expect(dwell.q25).toBe(fixture.expected_dwell.q25);
    expect(dwell.q75).toBe(fixture.expected_dwell.q75);
  });
});
