/**
 * Cross-language parity: the TS recovery-climatology math must reproduce, case
 * for case, the outputs Python recorded in tests/fixtures/parity_recovery.json.
 *
 * The fixture pins empirical_quantile (linear/type-7 interpolation) and the
 * conditional remaining-duration quantiles D - t | D > t, including the
 * outlived-the-population abstain branch. It is generated by
 * scripts/gen_recovery_parity_fixture.py and verified on the Python side by
 * tests/test_recovery_parity.py. This is the Worker half — if
 * worker/src/recovery.ts drifts from training/recovery_baseline.py, it fails
 * here.
 *
 * Regenerate the fixture with: uv run python -m scripts.gen_recovery_parity_fixture
 */

import { describe, expect, test } from 'vitest';

import fixture from '../../tests/fixtures/parity_recovery.json';
import { conditionalRemainingQuantiles, empiricalQuantile } from '../src/recovery';

interface RecoveryCase {
  label: string;
  fn: 'empirical_quantile' | 'conditional_remaining_quantiles';
  inputs: {
    sorted?: number[];
    q?: number;
    samples_min?: number[];
    elapsed_min?: number;
    min_samples?: number;
  };
  expected:
    | number
    | null
    | { p25: number; p50: number; p75: number; n: number };
}

const cases = fixture.cases as unknown as RecoveryCase[];
const TOL = 1e-9;

describe('recovery climatology parity with training/recovery_baseline.py', () => {
  for (const c of cases) {
    test(`${c.fn}: ${c.label}`, () => {
      if (c.fn === 'empirical_quantile') {
        const got = empiricalQuantile(c.inputs.sorted!, c.inputs.q!);
        expect(Math.abs(got - (c.expected as number)), c.label).toBeLessThanOrEqual(TOL);
        return;
      }
      const rq = conditionalRemainingQuantiles(
        c.inputs.samples_min!,
        c.inputs.elapsed_min!,
        c.inputs.min_samples!,
      );
      if (c.expected === null) {
        expect(rq, c.label).toBeNull();
        return;
      }
      const exp = c.expected as { p25: number; p50: number; p75: number; n: number };
      expect(rq, c.label).not.toBeNull();
      expect(Math.abs(rq!.p25 - exp.p25)).toBeLessThanOrEqual(TOL);
      expect(Math.abs(rq!.p50 - exp.p50)).toBeLessThanOrEqual(TOL);
      expect(Math.abs(rq!.p75 - exp.p75)).toBeLessThanOrEqual(TOL);
      expect(rq!.n).toBe(exp.n);
    });
  }
});
